# Generated by Django 2.0 on 2019-03-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_hour', '0002_auto_20190318_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherhour',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='weatherhour',
            name='time',
            field=models.DateTimeField(verbose_name='时间'),
        ),
    ]
