# Generated by Django 2.0 on 2019-03-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_hour', '0003_auto_20190318_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherhour',
            name='time',
            field=models.DateTimeField(unique=True, verbose_name='时间'),
        ),
    ]
